apiVersion: knetlab.rnp.br/v1
kind: Device
metadata:
  name: bot
  namespace: lab1
  actor: bot
spec:
  template:
    spec:
      containers:
        - name: bot
          image: 172.18.0.2:5000/nelson/t50:latest
          #image: ghcr.io/ngpjunior/t50
          #imagePullPolicy: IfNotPresent
          env:
            - name: SERVER
              value: "100"
            - name: BOTID
              value: "2"  
            - name: CLIENT
              value: "3"
            - name: NETINTERFACE
              value: "to-sw2"
            - name: PROTOCOL
              value: "TCP"

          command: ["/root/entry.sh"]
          #command: ["tail", "-f", "/dev/null"]
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          stdin: true
          tty: true
      
